# Generated by Django 4.1.5 on 2023-01-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveTime",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("start_time", models.DateTimeField()),
                ("close_time", models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name="quizpost",
            name="attempt_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quizpost",
            name="difficulty",
            field=models.TextField(default="easy"),
        ),
        migrations.AddField(
            model_name="quizpost",
            name="live",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quizpost",
            name="total_marks",
            field=models.IntegerField(default=None),
        ),
    ]
