# Generated by Django 4.1.5 on 2023-01-30 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_learnerprofile_rating_quizrecord_correct_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RatingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("rating", models.IntegerField()),
                ("affect_on", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name="quizrecord",
            name="attempt_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
